### ISSUE TITLE
There is no way to configure ident identification in config/application.properties

### ISSUE THREAD

**Issue by yuriiz** [dimagi/formplayer#180]
While performing this step:

    $ cp config/application.properties.example config/application.properties // Update properties as necessary

It is not possible to configure ident identification to postgresql database. Setting
```
datasource.hq.password=
datasource.formplayer.password=
```
Results in:
```
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "commcarehq"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:398)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:173)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:410)
	at org.postgresql.Driver.connect(Driver.java:280)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
```
(verified `psql formplayer` connects fine).
And removing this lines completely from application.properties results in:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private java.lang.String application.WebAppContext.hqPostgresPassword; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'datasource.hq.password' in string value "${datasource.hq.password}"
```

Similar error happens on omitting couchdb credentials.

**Comment by benrudolph** [comment]
Hi @yuriiz thanks for reporting. we've noticed it as well and are going to try and fix soon (work around being to add a password)
